### ISSUE TITLE
Make library usable on embedded devices

### ISSUE THREAD

**Issue by teythoon** [71/lesspass.rs#5]
I'd like to use lesspass on an embedded device, that means making it no_std and preferably also avoiding allocations and dependencies using allocations.  I have some patches towards this, but wanted to discuss #4 and the overall goal first.

**Comment by 71** [comment]
I think all allocations performed within the library itself can be avoided since we can compute the length of each vector ahead of time (and in some cases determine a constant upper bound). The problem is with the `num_bigint` dependency, which uses `Vec` behind the scenes and therefore allocates.

That bigint also has a constant maximum size (32 bytes), but I'm not aware of any `no_std` bigint library. Maybe we could provide our own implementation of these functions in `no_std`, with a potential loss of efficiency in that case?

**Comment by 71** [comment]
AFAIK, 21cfc8019cb26d7c870967b676cb050116498fcf makes the library fully `no_std` compatible. There are no `no_std` specific tests, though. Feel free to add some if you want (especially for corner cases, like having long entropy buffers).
